name: With PR Comment
on: pull_request

jobs:
  # <----------------- BASIC WITHOUT PR ------------------>
  pr:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: PR Test
        uses: ./
        with:
          commit-email: sean@erzz.com
          plan-files: test-data/
          output-filename: test-data/plan-pr.png
          pr-comment: true
